// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-axios';
import type { CheckHealthData, CheckHealthResponses, GetUsersData, GetUsersResponses, AddUserData, AddUserResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class V1BaseHealthService {
    /**
     * Get health
     */
    public static checkHealth<ThrowOnError extends boolean = true>(options?: Options<CheckHealthData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<CheckHealthResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/v1/health',
            ...options
        });
    }
    
}

export class V1BaseUsersService {
    /**
     * Get users
     */
    public static getUsers<ThrowOnError extends boolean = true>(options?: Options<GetUsersData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetUsersResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/v1/users',
            ...options
        });
    }
    
    /**
     * Add user
     */
    public static addUser<ThrowOnError extends boolean = true>(options?: Options<AddUserData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<AddUserResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/v1/users/add',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}