// This file is auto-generated by @hey-api/openapi-ts

export type AddUserInput = {
    age: number;
    name: string;
};

export type ModelUser = {
    age: number;
    id: number;
    name: string;
};

export type ModelUserList = {
    count: number;
    items: Array<ModelUser>;
};

export type CheckHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/health';
};

export type CheckHealthResponses = {
    /**
     * OK
     */
    200: string;
};

export type CheckHealthResponse = CheckHealthResponses[keyof CheckHealthResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users';
};

export type GetUsersResponses = {
    /**
     * OK
     */
    200: ModelUserList;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type AddUserData = {
    body?: AddUserInput;
    path?: never;
    query?: never;
    url: '/v1/users/add';
};

export type AddUserResponses = {
    /**
     * OK
     */
    200: string;
};

export type AddUserResponse = AddUserResponses[keyof AddUserResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};