// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zAddUserInput = z.object({
    age: z.number().int(),
    name: z.string()
});

export const zModelUser = z.object({
    age: z.number().int(),
    id: z.number().int(),
    name: z.string()
});

export const zModelUserList = z.object({
    count: z.number().int(),
    items: z.array(zModelUser)
});

/**
 * OK
 */
export const zCheckHealthResponse = z.string();

/**
 * OK
 */
export const zGetUsersResponse = zModelUserList;

export const zAddUserData = zAddUserInput;

/**
 * OK
 */
export const zAddUserResponse = z.string();