export const base_colors = {
  white: '#FFFFFF',
  dark: {
    600: '#25292C',
    500: '#37393B',
    300: '#939AA1',
  },
  grey: '#EEEEEE',
  blue: {
    500: '#4B94F6',
    400: '#51A2FF',
  },
  green: {
    500: '#15B357',
    300: '#5DDD92',
    200: '#B9F8CF',
  },
  red: {
    500: '#DD5D5D',
    200: '#f89696',
  },
  slate: {
    50: '#f8fafc',
    100: '#f1f5f9',
    200: '#e2e8f0',
    300: '#cbd5e1',
    400: '#94a3b8',
    500: '#64748b',
    600: '#475569',
    700: '#334155',
    800: '#1e293b',
    900: '#0f172a',
    950: '#020617',
  },
};

export const dark = {
  'dark-background-background': base_colors.white,
  'dark-background-secondary': base_colors.slate[100],
  'dark-table-header-bg': base_colors.slate[200],
  'dark-table-cell-bg': base_colors.slate[100],
  'dark-text-lines': base_colors.slate[900],
  'dark-text-lines-active': base_colors.white,
  'dark-text-hover': base_colors.blue[500],
  'dark-text-secondary': base_colors.slate[500],
  'dark-text-light': base_colors.slate[600],
  'dark-text-green': base_colors.green[500],
  'dark-text-red': base_colors.red[500],
  'dark-button-bg': base_colors.slate[700],
  'dark-button-bg-secondary': base_colors.slate[200],
  'dark-button-bg-hover': base_colors.blue[400],
  'dark-button-text': base_colors.white,
  'dark-button-text-secondary': base_colors.slate[900],
  'dark-button-icon': base_colors.white,
  'dark-button-icon-secondary': base_colors.slate[500],
  'dark-check-fill': base_colors.slate[100],
  'dark-border-lines': base_colors.slate[200],
  'dark-menu-bg': base_colors.slate[700],
};

export const light = {
  'background-background': base_colors.white,
  'background-secondary': base_colors.slate[100],
  highlight: base_colors.slate[100],
  'highlight-emphasis': base_colors.slate[200],
  'table-header-bg': base_colors.slate[200],
  'table-cell-bg': base_colors.slate[50],
  'text-lines': base_colors.slate[900],
  'text-lines-active': base_colors.white,
  'text-hover': base_colors.blue[500],
  'text-secondary': base_colors.slate[500],
  'text-light': base_colors.slate[400],
  'text-green': base_colors.green[500],
  'text-red': base_colors.red[500],
  'button-bg': base_colors.slate[700],
  'button-bg-secondary': base_colors.slate[200],
  'button-bg-hover': base_colors.blue[400],
  'button-text': base_colors.white,
  'button-text-secondary': base_colors.slate[900],
  'button-icon': base_colors.white,
  'button-icon-secondary': base_colors.slate[500],
  'check-fill': base_colors.slate[100],
  'border-lines': base_colors.slate[200],
  'menu-bg': base_colors.slate[700],
};

export const colors = {
  ...base_colors,
  ...light,
  ...dark,
};
