// This file is auto-generated by @hey-api/openapi-ts

import { type Options, V1BaseHealthService, V1BaseUsersService } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/vue-query';
import type { CheckHealthData, GetUsersData, AddUserData, AddUserResponse } from '../types.gen';
import type { AxiosError } from 'axios';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: (options?.client ?? _heyApiClient).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const checkHealthQueryKey = (options?: Options<CheckHealthData>) => createQueryKey('checkHealth', options);

/**
 * Get health
 */
export const checkHealthOptions = (options?: Options<CheckHealthData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await V1BaseHealthService.checkHealth({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: checkHealthQueryKey(options)
    });
};

export const getUsersQueryKey = (options?: Options<GetUsersData>) => createQueryKey('getUsers', options);

/**
 * Get users
 */
export const getUsersOptions = (options?: Options<GetUsersData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await V1BaseUsersService.getUsers({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUsersQueryKey(options)
    });
};

export const addUserQueryKey = (options?: Options<AddUserData>) => createQueryKey('addUser', options);

/**
 * Add user
 */
export const addUserOptions = (options?: Options<AddUserData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await V1BaseUsersService.addUser({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: addUserQueryKey(options)
    });
};

/**
 * Add user
 */
export const addUserMutation = (options?: Partial<Options<AddUserData>>): UseMutationOptions<AddUserResponse, AxiosError<DefaultError>, Options<AddUserData>> => {
    const mutationOptions: UseMutationOptions<AddUserResponse, AxiosError<DefaultError>, Options<AddUserData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await V1BaseUsersService.addUser({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};